### ISSUE TITLE
Repeated ECONNRESET errors in setup-dotnet action

### ISSUE THREAD

**Issue by AaronFriel** [actions/setup-dotnet#333]
**Description:**

Roughly 70% of merge jobs in the pulumi/pulumi repo are failing due to a high failure rate on actions/setup-dotnet@v2.

No additional logs are present. We are running with these arguments:

```yaml
  with:
    dotnet-version: 6.0.x
    include-prerelease: false
```

![Image showing "Run actions/setup-dotnet@v2" and "Error: read ECONNRESET"](https://user-images.githubusercontent.com/788800/195216698-fe398cfe-6146-4c46-afa7-8128ea5239e7.png)

**Task version:**

actions/setup-dotnet@v2

**Platform:**
- [x] Ubuntu, example: https://github.com/pulumi/pulumi/actions/runs/3223023912/jobs/5272739307
- [x] macOS, example: https://github.com/pulumi/pulumi/actions/runs/3227143235/jobs/5281716689
- [x] Windows, example: https://github.com/pulumi/pulumi/actions/runs/3222484557/jobs/5271676054

Failures have occurred on all three platforms.

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Unsure of steps to reproduce - we run a large number of jobs to validate all merges (on the order of ~100), and in more than half of the workflows in the past 24 hours the workflow failed due to 

**Expected behavior:**

Action should succeed.

**Actual behavior:**

Action fails catastrophically on a network issue. 

Example failures:

1. https://github.com/pulumi/pulumi/actions/runs/3222484557/jobs/5271676054
1. https://github.com/pulumi/pulumi/actions/runs/3223023912/jobs/5272739307
1. https://github.com/pulumi/pulumi/actions/runs/3223183376/jobs/5273031068
1. https://github.com/pulumi/pulumi/actions/runs/3227143235/jobs/5281716689
1. https://github.com/pulumi/pulumi/actions/runs/3228086473/jobs/5283821713
1. https://github.com/pulumi/pulumi/actions/runs/3227884171/jobs/5283427013
1. https://github.com/pulumi/pulumi/actions/runs/3230504739/jobs/5289102856
1. https://github.com/pulumi/pulumi/actions/runs/3230628127/jobs/5289317304
1. https://github.com/pulumi/pulumi/actions/runs/3230757326/jobs/5289634185
1. https://github.com/pulumi/pulumi/actions/runs/3230757326/jobs/5289636076

**Comment by IvanZosimov** [comment]
Hi, @AaronFriel 👋 I see the problem in your repo, but unfortunately, I can't reproduce it. It was probably a temporary problem on the side of the [MS .NET SDKs dist](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json), our action relies on it and it explains why the installation of SDK for all OS was blocked.

**Comment by AaronFriel** [comment]
@IvanZosimov Would it make sense to engineer around this or mirror their distribution info?

Would it be possible to add some logging to this action so that when net requests fail, the URL requested is logged?

**Comment by IvanZosimov** [comment]
@AaronFriel , Sure! We are working on this issue now.

**Comment by rcdailey** [comment]
I'm getting this error now: https://github.com/recyclarr/recyclarr/actions/runs/3252206657/jobs/5338195677#step:3:36

**Comment by joelwkall** [comment]
I'm also seeing this. Not sure if it helps, but this is the error:
```
Sun, 16 Oct 2022 19:17:43 GMT
Run actions/setup-dotnet@v2
  with:
    dotnet-version: 5.0.x
    include-prerelease: false

Sun, 16 Oct 2022 19:17:44 GMT
Error: read ECONNRESET
```

This is my workflow yml:

```
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
```

**Comment by IvanZosimov** [comment]
Hi, @rcdailey and @joelwkall, thanks for your comments. We are still in the process of investigation. You can upgrade the version of the `setup-dotnet` action to `v3` because it's less influenced by the error.

**Comment by diogokiss** [comment]
I'm also quite often facing this issue using this GitHub Action. 😢

**Comment by MaksimZhukov** [comment]
Hello everyone!
We have released [new action version](https://github.com/actions/setup-dotnet/releases/tag/v3.0.3) with a fix for this issue. Feel free to use the `v3` tag.
Thank you for the patience!

**Comment by dmitry-shibanov** [comment]
For now I'm going to close the issue. If you have any concerns feel free to ping us.
